# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170114_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('dipp', models.IntegerField(max_length=50)),
            ],
        ),
    ]
