# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170123_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdipp',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdipp',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
