# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170124_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdipp',
            name='user',
        ),
    ]
