# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170124_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdipp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
