# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170124_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brankName', models.CharField(max_length=100)),
                ('typeOfBusiness', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('B2B2C', 'B2B2C')], max_length=6)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=256)),
                ('videoLink', models.CharField(max_length=256)),
                ('investor', models.CharField(max_length=256)),
                ('userdipp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserDipp')),
            ],
        ),
    ]
