# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='brankName',
            new_name='brandName',
        ),
    ]
