# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170127_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aboutProductCompany',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
