# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170127_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aboutProductCompany',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
