# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170127_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('userdipp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserDipp')),
            ],
        ),
    ]
