# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170127_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='userdipp',
            new_name='profile',
        ),
    ]
