# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170301_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typeOfBusiness',
            field=models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('C2B', 'C2B'), ('B2B2C', 'B2B2C')], max_length=6),
        ),
    ]
