# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20170302_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aboutProductCompany',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='investor',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
