# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20170302_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutProductCompany',
            field=models.CharField(default='asas', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='brandName',
            field=models.CharField(default='asas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='sdsd', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='investor',
            field=models.FileField(default='dsdsd', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.FileField(default='sadasd', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='projectName',
            field=models.CharField(default='sadasd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='typeOfBusiness',
            field=models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('C2B', 'C2B'), ('B2B2C', 'B2B2C')], default='B2B', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(default='sdasdas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='videoLink',
            field=models.CharField(default='fsaafas', max_length=256),
            preserve_default=False,
        ),
    ]
