# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20170302_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='investor',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
