# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20170302_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aboutProductCompany',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='brandName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projectName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='typeOfBusiness',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='videoLink',
        ),
        migrations.AlterField(
            model_name='project',
            name='investor',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
