# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20170303_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectName',
            new_name='companyName',
        ),
    ]
