# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_profile_profiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aboutProductCompany',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
