# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CategoryFk',
        ),
    ]
